?column?
"insert into event_markets (event_code, market) values ('EVEAGWDVHHHZS', 'MN');"
"insert into event_markets (event_code, market) values ('EVEAHGSQPMQFV', 'MN');"
"insert into event_markets (event_code, market) values ('EVEASEXEQDDTO', 'TX');"
"insert into event_markets (event_code, market) values ('EVEAUIJGTGIKH', 'EXCLUDE');"
"insert into event_markets (event_code, market) values ('EVEAWTGFPPFSM', 'IL');"
"insert into event_markets (event_code, market) values ('EVEBEIBGHBBDY', 'VIRTUAL');"
"insert into event_markets (event_code, market) values ('EVEBEMAYUTFRN', 'MO');"
"insert into event_markets (event_code, market) values ('EVEBIGGSQYHNN', 'MO');"
"insert into event_markets (event_code, market) values ('EVEBIIDDCIRPI', 'IL');"
"insert into event_markets (event_code, market) values ('EVEBINUGGXXVF', 'MI');"
"insert into event_markets (event_code, market) values ('EVEBMFUWHTZSA', 'MN');"
"insert into event_markets (event_code, market) values ('EVEBMHCSSVXIM', 'OH');"
"insert into event_markets (event_code, market) values ('EVEBMLCJGEKQD', 'MN');"
"insert into event_markets (event_code, market) values ('EVEBNDGYCDSPU', 'MN');"
"insert into event_markets (event_code, market) values ('EVEBOXAESRZZA', 'TX');"
"insert into event_markets (event_code, market) values ('EVEBSKEOMMHEY', 'IL');"
"insert into event_markets (event_code, market) values ('EVEBVXBHCFLJG', 'MN');"
"insert into event_markets (event_code, market) values ('EVEBVXNGDUXAC', 'TX');"
"insert into event_markets (event_code, market) values ('EVEBXKBJHJKSH', 'IL');"
"insert into event_markets (event_code, market) values ('EVEBYIINAOBDH', 'TN');"
"insert into event_markets (event_code, market) values ('EVEBZEWKDUMXM', 'MN');"
"insert into event_markets (event_code, market) values ('EVECFCDQHPARL', 'VIRTUAL');"
"insert into event_markets (event_code, market) values ('EVECFMTDGFNOT', 'OH');"
"insert into event_markets (event_code, market) values ('EVECGQASYZGCC', 'IN');"
"insert into event_markets (event_code, market) values ('EVECKCNLOXYTQ', 'MN');"
"insert into event_markets (event_code, market) values ('EVECMOXGHRQMZ', 'TX');"
"insert into event_markets (event_code, market) values ('EVECNHDFQBIBR', 'MN');"
"insert into event_markets (event_code, market) values ('EVECOHZWKTBOL', 'TX');"
"insert into event_markets (event_code, market) values ('EVECRAZALWFDT', 'MN');"
"insert into event_markets (event_code, market) values ('EVECTXDZEXNNU', 'TX');"
"insert into event_markets (event_code, market) values ('EVECVNAFMTPYE', 'ND');"
"insert into event_markets (event_code, market) values ('EVEDBQTRVFBYG', 'MN');"
"insert into event_markets (event_code, market) values ('EVEDCHAZCXHLI', 'ND');"
"insert into event_markets (event_code, market) values ('EVEDCQUVSDGTL', 'MN');"
"insert into event_markets (event_code, market) values ('EVEDHPXIKLSEE', 'WI');"
"insert into event_markets (event_code, market) values ('EVEDIVKIPMYTD', 'MO');"
"insert into event_markets (event_code, market) values ('EVEDJNIKBYQGV', 'MN');"
"insert into event_markets (event_code, market) values ('EVEDJOUTYQOHS', 'MN');"
"insert into event_markets (event_code, market) values ('EVEDKCGQAPMVQ', 'MN');"
"insert into event_markets (event_code, market) values ('EVEDLDQQKGIXM', 'TX');"
"insert into event_markets (event_code, market) values ('EVEDPNPBIGIPN', 'TX');"
"insert into event_markets (event_code, market) values ('EVEDQURACZWNF', 'MN');"
"insert into event_markets (event_code, market) values ('EVEDYMLAQVZQS', 'IL');"
"insert into event_markets (event_code, market) values ('EVEDYXKFLSQVV', 'MN');"
"insert into event_markets (event_code, market) values ('EVEEAIKYXHVMT', 'IL');"
"insert into event_markets (event_code, market) values ('EVEEERIHLAXXZ', 'MI');"
"insert into event_markets (event_code, market) values ('EVEEIRCZREYPI', 'IL');"
"insert into event_markets (event_code, market) values ('EVEEJTLIYCWEK', 'TX');"
"insert into event_markets (event_code, market) values ('EVEELEBDJNKCP', 'MN');"
"insert into event_markets (event_code, market) values ('EVEEOSSGUXLJR', 'OH');"
"insert into event_markets (event_code, market) values ('EVEEPEBJPYXLG', 'MN');"
"insert into event_markets (event_code, market) values ('EVEESMCLNSGKN', 'TX');"
"insert into event_markets (event_code, market) values ('EVEESXNUGXMZR', 'MN');"
"insert into event_markets (event_code, market) values ('EVEETTVLYFYUM', 'VIRTUAL');"
"insert into event_markets (event_code, market) values ('EVEEVFWPTUQKS', 'MN');"
"insert into event_markets (event_code, market) values ('EVEEZKTOXEKRA', 'MN');"
"insert into event_markets (event_code, market) values ('EVEFEUVACQUVX', 'OH');"
"insert into event_markets (event_code, market) values ('EVEFJDGVZISNP', 'MN');"
"insert into event_markets (event_code, market) values ('EVEFQBQOKWAGW', 'IL');"
"insert into event_markets (event_code, market) values ('EVEFQCCBSUXVA', 'TX');"
"insert into event_markets (event_code, market) values ('EVEFQMLGTOOBB', 'MN');"
"insert into event_markets (event_code, market) values ('EVEGEGXFJHNAF', 'MN');"
"insert into event_markets (event_code, market) values ('EVEGEPEFLWEZW', 'MN');"
"insert into event_markets (event_code, market) values ('EVEGFSDJUBXSD', 'NE');"
"insert into event_markets (event_code, market) values ('EVEGGHDCRWPCR', 'MN');"
"insert into event_markets (event_code, market) values ('EVEGKJCBMDHGC', 'OH');"
"insert into event_markets (event_code, market) values ('EVEGKKYZIUAER', 'MN');"
"insert into event_markets (event_code, market) values ('EVEGLXUNIPPXX', 'IL');"
"insert into event_markets (event_code, market) values ('EVEGNZEREJYGA', 'MN');"
"insert into event_markets (event_code, market) values ('EVEGPAKZEDVPH', 'OH');"
"insert into event_markets (event_code, market) values ('EVEGQISEQQNUR', 'MN');"
"insert into event_markets (event_code, market) values ('EVEGQYNICCMMD', 'MN');"
"insert into event_markets (event_code, market) values ('EVEGSXXIXZCXX', 'MN');"
"insert into event_markets (event_code, market) values ('EVEGUTAIDRZXL', 'MN');"
"insert into event_markets (event_code, market) values ('EVEGYDHRIUFOX', 'TX');"
"insert into event_markets (event_code, market) values ('EVEGYGDHXYZYL', 'TX');"
"insert into event_markets (event_code, market) values ('EVEHBRAQLKRRV', 'MN');"
"insert into event_markets (event_code, market) values ('EVEHCVWRYQACD', 'MN');"
"insert into event_markets (event_code, market) values ('EVEHEVRELXEKO', 'MI');"
"insert into event_markets (event_code, market) values ('EVEHFHIBUSSPZ', 'MO');"
"insert into event_markets (event_code, market) values ('EVEHHBKGPZKQY', 'IL');"
"insert into event_markets (event_code, market) values ('EVEHIVFZDQUDV', 'TX');"
"insert into event_markets (event_code, market) values ('EVEHKEWGZZZXF', 'EXCLUDE');"
"insert into event_markets (event_code, market) values ('EVEHMQNDUQFPM', 'TX');"
"insert into event_markets (event_code, market) values ('EVEHNADREXBHR', 'MN');"
"insert into event_markets (event_code, market) values ('EVEHOMHNHCKMR', 'IL');"
"insert into event_markets (event_code, market) values ('EVEHPLENHLUOG', 'IL');"
"insert into event_markets (event_code, market) values ('EVEHQCWNNOEBV', 'IL');"
"insert into event_markets (event_code, market) values ('EVEHXAUQRENMP', 'TX');"
"insert into event_markets (event_code, market) values ('EVEIEZYNJZXXQ', 'EXCLUDE');"
"insert into event_markets (event_code, market) values ('EVEIKBUBYSMIN', 'MO');"
"insert into event_markets (event_code, market) values ('EVEIKYYUBMAUF', 'TX');"
"insert into event_markets (event_code, market) values ('EVEIKZQWWGNBM', 'TN');"
"insert into event_markets (event_code, market) values ('EVEIMRDGLPSAI', 'MN');"
"insert into event_markets (event_code, market) values ('EVEINMXHHSYLF', 'MN');"
"insert into event_markets (event_code, market) values ('EVEIPSVVTDMCC', 'MN');"
"insert into event_markets (event_code, market) values ('EVEJBZKQCVLNM', 'OH');"
"insert into event_markets (event_code, market) values ('EVEJGOYMAIDGR', 'MN');"
"insert into event_markets (event_code, market) values ('EVEJIMXTHFSAA', 'TX');"
"insert into event_markets (event_code, market) values ('EVEJLWMVTYXRT', 'MN');"
"insert into event_markets (event_code, market) values ('EVEJOFFWQUYCX', 'MN');"
"insert into event_markets (event_code, market) values ('EVEJOGFTURRYR', 'MN');"
"insert into event_markets (event_code, market) values ('EVEJPRCDFZFUS', 'IN');"
"insert into event_markets (event_code, market) values ('EVEJSSOBPSXZE', 'TX');"
"insert into event_markets (event_code, market) values ('EVEJSVAMXAVOB', 'IL');"
"insert into event_markets (event_code, market) values ('EVEJUWDAISSZV', 'TX');"
"insert into event_markets (event_code, market) values ('EVEJUXPNWYGDD', 'TX');"
"insert into event_markets (event_code, market) values ('EVEJWTIKJWKZE', 'MI');"
"insert into event_markets (event_code, market) values ('EVEJYDDDZGRXW', 'MN');"
"insert into event_markets (event_code, market) values ('EVEJZVTJONPBJ', 'IL');"
"insert into event_markets (event_code, market) values ('EVEKBWUTCYBED', 'EXCLUDE');"
"insert into event_markets (event_code, market) values ('EVEKCLLOCQCAW', 'MN');"
"insert into event_markets (event_code, market) values ('EVEKDYPFJLMRT', 'MO');"
"insert into event_markets (event_code, market) values ('EVEKGRBRXMBSW', 'IL');"
"insert into event_markets (event_code, market) values ('EVEKMHQFUYTZQ', 'MN');"
"insert into event_markets (event_code, market) values ('EVEKMKHTYHVBG', 'IN');"
"insert into event_markets (event_code, market) values ('EVEKQJDKWCSTG', 'FL');"
"insert into event_markets (event_code, market) values ('EVEKXRFVNCMBP', 'EXCLUDE');"
"insert into event_markets (event_code, market) values ('EVELCEUKNLUAI', 'IL');"
"insert into event_markets (event_code, market) values ('EVELFDAXDEBDE', 'MN');"
"insert into event_markets (event_code, market) values ('EVELHPQUZJTGP', 'MN');"
"insert into event_markets (event_code, market) values ('EVELKXHWZJZZP', 'TX');"
"insert into event_markets (event_code, market) values ('EVELMSBTRKGPB', 'MN');"
"insert into event_markets (event_code, market) values ('EVELNOHWZWMDG', 'MN');"
"insert into event_markets (event_code, market) values ('EVELNQRDOCGUT', 'IL');"
"insert into event_markets (event_code, market) values ('EVELNTSGLAJPS', 'NE');"
"insert into event_markets (event_code, market) values ('EVELPZABMWBGR', 'WI');"
"insert into event_markets (event_code, market) values ('EVELQQQQHFHEU', 'IL');"
"insert into event_markets (event_code, market) values ('EVELSTBBWNXJX', 'MN');"
"insert into event_markets (event_code, market) values ('EVELSUJZQPKYM', 'TX');"
"insert into event_markets (event_code, market) values ('EVELVLIBWBMIC', 'WI');"
"insert into event_markets (event_code, market) values ('EVELXCOXFSRWX', 'TX');"
"insert into event_markets (event_code, market) values ('EVELZHXMHMQSB', 'IL');"
"insert into event_markets (event_code, market) values ('EVEMBCXJGREWM', 'MN');"
"insert into event_markets (event_code, market) values ('EVEMBJBBAYVRO', 'MN');"
"insert into event_markets (event_code, market) values ('EVEMBRYGMXHAI', 'NE');"
"insert into event_markets (event_code, market) values ('EVEMGIUCAGGYR', 'MN');"
"insert into event_markets (event_code, market) values ('EVEMGLTUGPBWL', 'MO');"
"insert into event_markets (event_code, market) values ('EVEMKAHSICZMC', 'MN');"
"insert into event_markets (event_code, market) values ('EVEMNBDYHPQLY', 'MN');"
"insert into event_markets (event_code, market) values ('EVEMPHYWTJIJE', 'IL');"
"insert into event_markets (event_code, market) values ('EVEMQKJTCVPEX', 'MT');"
"insert into event_markets (event_code, market) values ('EVEMSHJEWSTFY', 'MO');"
"insert into event_markets (event_code, market) values ('EVEMWDJELWVUA', 'TX');"
"insert into event_markets (event_code, market) values ('EVEMWHFOJQCBT', 'MN');"
"insert into event_markets (event_code, market) values ('EVEMYGPTKYTRC', 'MI');"
"insert into event_markets (event_code, market) values ('EVENBLERZLPSF', 'TX');"
"insert into event_markets (event_code, market) values ('EVENHDHDIIHVZ', 'MN');"
"insert into event_markets (event_code, market) values ('EVENHNJGQJDQU', 'MN');"
"insert into event_markets (event_code, market) values ('EVENMHBPHMHMU', 'WI');"
"insert into event_markets (event_code, market) values ('EVENOWVPWZMTV', 'EXCLUDE');"
"insert into event_markets (event_code, market) values ('EVENQJAXAOVCF', 'TX');"
"insert into event_markets (event_code, market) values ('EVENQXTHXYCGL', 'MN');"
"insert into event_markets (event_code, market) values ('EVENSZWYQSGFR', 'WI');"
"insert into event_markets (event_code, market) values ('EVENTWNGJOIJH', 'MI');"
"insert into event_markets (event_code, market) values ('EVENVQPXKOSSU', 'MN');"
"insert into event_markets (event_code, market) values ('EVENYAGKIFWMP', 'MN');"
"insert into event_markets (event_code, market) values ('EVENYNNDLIANH', 'MN');"
"insert into event_markets (event_code, market) values ('EVEOAHTXFGEMR', 'OH');"
"insert into event_markets (event_code, market) values ('EVEOAKBEGTYMM', 'TX');"
"insert into event_markets (event_code, market) values ('EVEOBKGMBSFKG', 'TX');"
"insert into event_markets (event_code, market) values ('EVEOEKYZATXBH', 'OH');"
"insert into event_markets (event_code, market) values ('EVEOGLVTIAPOR', 'IA');"
"insert into event_markets (event_code, market) values ('EVEOGTIRSUILT', 'IA');"
"insert into event_markets (event_code, market) values ('EVEOIINUQBQAI', 'IL');"
"insert into event_markets (event_code, market) values ('EVEOIVNMRSMOJ', 'TX');"
"insert into event_markets (event_code, market) values ('EVEOKXJIRAZNE', 'MN');"
"insert into event_markets (event_code, market) values ('EVEOPBCDFNGFT', 'IL');"
"insert into event_markets (event_code, market) values ('EVEORFJEVKMPN', 'MN');"
"insert into event_markets (event_code, market) values ('EVEOVOZKJUXYD', 'EXCLUDE');"
"insert into event_markets (event_code, market) values ('EVEOVRHPLZFJU', 'OH');"
"insert into event_markets (event_code, market) values ('EVEOYIFPWSSQB', 'MN');"
"insert into event_markets (event_code, market) values ('EVEPADDBRBEJU', 'MN');"
"insert into event_markets (event_code, market) values ('EVEPBEJPRFEQO', 'TX');"
"insert into event_markets (event_code, market) values ('EVEPCTTQERUEG', 'ND');"
"insert into event_markets (event_code, market) values ('EVEPCZTULIAFU', 'MI');"
"insert into event_markets (event_code, market) values ('EVEPISRMQXRQH', 'TX');"
"insert into event_markets (event_code, market) values ('EVEPIYSPUJMRM', 'TX');"
"insert into event_markets (event_code, market) values ('EVEPKYRPCQZMN', 'EXCLUDE');"
"insert into event_markets (event_code, market) values ('EVEPLEJYDHZES', 'TX');"
"insert into event_markets (event_code, market) values ('EVEPMYJZJEPCE', 'MN');"
"insert into event_markets (event_code, market) values ('EVEPNMCSKZENL', 'MN');"
"insert into event_markets (event_code, market) values ('EVEPOLKISZTBG', 'TX');"
"insert into event_markets (event_code, market) values ('EVEPPXOECVMEG', 'TX');"
"insert into event_markets (event_code, market) values ('EVEPQJVUFGTNA', 'MO');"
"insert into event_markets (event_code, market) values ('EVEPRFBTCUFHI', 'TX');"
"insert into event_markets (event_code, market) values ('EVEPTRSLTNALT', 'MO');"
"insert into event_markets (event_code, market) values ('EVEPXPZLKXJQC', 'IL');"
"insert into event_markets (event_code, market) values ('EVEQCZIMGCBGP', 'MI');"
"insert into event_markets (event_code, market) values ('EVEQDTYPCJWMZ', 'MN');"
"insert into event_markets (event_code, market) values ('EVEQFNDXMNEJB', 'TX');"
"insert into event_markets (event_code, market) values ('EVEQGCZENYDXK', 'MO');"
"insert into event_markets (event_code, market) values ('EVEQIPNXSVAXR', 'MN');"
"insert into event_markets (event_code, market) values ('EVEQMFDLWUMFY', 'TX');"
"insert into event_markets (event_code, market) values ('EVEQNXBFQHGKL', 'IL');"
"insert into event_markets (event_code, market) values ('EVEQPURHBKAQV', 'TX');"
"insert into event_markets (event_code, market) values ('EVEQRNVWEZZNU', 'MN');"
"insert into event_markets (event_code, market) values ('EVEQSNEHPFXEC', 'MN');"
"insert into event_markets (event_code, market) values ('EVEQUICWHBOOR', 'TX');"
"insert into event_markets (event_code, market) values ('EVEQXKLKKCIGX', 'MN');"
"insert into event_markets (event_code, market) values ('EVERAWRXGUSZJ', 'KY');"
"insert into event_markets (event_code, market) values ('EVERDRRPJZGCM', 'MN');"
"insert into event_markets (event_code, market) values ('EVERFPFETHAAK', 'MN');"
"insert into event_markets (event_code, market) values ('EVERFULLNIHNJ', 'MI');"
"insert into event_markets (event_code, market) values ('EVERHTQFUXALL', 'IL');"
"insert into event_markets (event_code, market) values ('EVERHXTQNABQV', 'MN');"
"insert into event_markets (event_code, market) values ('EVERKNVYKYKSF', 'VIRTUAL');"
"insert into event_markets (event_code, market) values ('EVERMZZEUTAAC', 'WI');"
"insert into event_markets (event_code, market) values ('EVERQRMIWJTJW', 'IL');"
"insert into event_markets (event_code, market) values ('EVERSNROIJVCZ', 'TX');"
"insert into event_markets (event_code, market) values ('EVERSQVCIWTBY', 'WI');"
"insert into event_markets (event_code, market) values ('EVERSXXROROIS', 'MN');"
"insert into event_markets (event_code, market) values ('EVERUBKZWHZMM', 'MN');"
"insert into event_markets (event_code, market) values ('EVESBHMZSGSJD', 'MN');"
"insert into event_markets (event_code, market) values ('EVESCJSDTMOKA', 'MN');"
"insert into event_markets (event_code, market) values ('EVESCPRHZIVFP', 'MN');"
"insert into event_markets (event_code, market) values ('EVESHQOBPEIXT', 'MN');"
"insert into event_markets (event_code, market) values ('EVESKNGXBSUXZ', 'MN');"
"insert into event_markets (event_code, market) values ('EVESLFCSKAQMJ', 'MN');"
"insert into event_markets (event_code, market) values ('EVESTZHAETYYD', 'MO');"
"insert into event_markets (event_code, market) values ('EVESUCNYUYVOB', 'TX');"
"insert into event_markets (event_code, market) values ('EVESZBDHFTNKO', 'IL');"
"insert into event_markets (event_code, market) values ('EVETCRMGFTHRV', 'MN');"
"insert into event_markets (event_code, market) values ('EVETHIKVMONLC', 'IL');"
"insert into event_markets (event_code, market) values ('EVETKFKZYORSV', 'TX');"
"insert into event_markets (event_code, market) values ('EVETMJITKBUEG', 'VIRTUAL');"
"insert into event_markets (event_code, market) values ('EVETNSTMJHUGD', 'MN');"
"insert into event_markets (event_code, market) values ('EVETYIRXUEXZW', 'MN');"
"insert into event_markets (event_code, market) values ('EVEUIIUBLZPTY', 'IL');"
"insert into event_markets (event_code, market) values ('EVEUJLXCWLFBJ', 'MN');"
"insert into event_markets (event_code, market) values ('EVEURKWYFRVOY', 'MN');"
"insert into event_markets (event_code, market) values ('EVEURUGVZYVXR', 'MN');"
"insert into event_markets (event_code, market) values ('EVEUTWRNMCSRD', 'NE');"
"insert into event_markets (event_code, market) values ('EVEUUDVIFYNTI', 'TX');"
"insert into event_markets (event_code, market) values ('EVEUUFXBUQKYG', 'TX');"
"insert into event_markets (event_code, market) values ('EVEUVHFBWMKHQ', 'OH');"
"insert into event_markets (event_code, market) values ('EVEUVQXGRWFEU', 'MN');"
"insert into event_markets (event_code, market) values ('EVEVABQSVMMXS', 'TX');"
"insert into event_markets (event_code, market) values ('EVEVDZWSVHEJU', 'MN');"
"insert into event_markets (event_code, market) values ('EVEVGPPZMMMUI', 'MN');"
"insert into event_markets (event_code, market) values ('EVEVJGCAGSCEA', 'OH');"
"insert into event_markets (event_code, market) values ('EVEVJMXDXYUKO', 'EXCLUDE');"
"insert into event_markets (event_code, market) values ('EVEVLISBBDLXJ', 'TX');"
"insert into event_markets (event_code, market) values ('EVEVNBKMGMJVL', 'MI');"
"insert into event_markets (event_code, market) values ('EVEVOWLOEENME', 'EXCLUDE');"
"insert into event_markets (event_code, market) values ('EVEVQYORUPNFL', 'MN');"
"insert into event_markets (event_code, market) values ('EVEVSAFPHTOFH', 'IL');"
"insert into event_markets (event_code, market) values ('EVEVTELDDLNDR', 'EXCLUDE');"
"insert into event_markets (event_code, market) values ('EVEVZVUFLNBMG', 'MI');"
"insert into event_markets (event_code, market) values ('EVEWDHAGDQLFD', 'MN');"
"insert into event_markets (event_code, market) values ('EVEWDTNUGHXRF', 'IL');"
"insert into event_markets (event_code, market) values ('EVEWDVUUAINJS', 'MN');"
"insert into event_markets (event_code, market) values ('EVEWFDDIGJKFW', 'MN');"
"insert into event_markets (event_code, market) values ('EVEWKLJPIHMBB', 'MI');"
"insert into event_markets (event_code, market) values ('EVEWMYEDARIKF', 'TX');"
"insert into event_markets (event_code, market) values ('EVEWPRLXCDWXJ', 'MO');"
"insert into event_markets (event_code, market) values ('EVEWVRQFGBQTB', 'MO');"
"insert into event_markets (event_code, market) values ('EVEWWVPEJTUXP', 'MN');"
"insert into event_markets (event_code, market) values ('EVEWZBBDJIJJJ', 'IL');"
"insert into event_markets (event_code, market) values ('EVEWZJUWFVVDC', 'IN');"
"insert into event_markets (event_code, market) values ('EVEXDFIXUWYGL', 'EXCLUDE');"
"insert into event_markets (event_code, market) values ('EVEXFVFAXWGLU', 'TX');"
"insert into event_markets (event_code, market) values ('EVEXIQZXZWIQM', 'TX');"
"insert into event_markets (event_code, market) values ('EVEXQAMDMEYJH', 'IL');"
"insert into event_markets (event_code, market) values ('EVEXVJMXBYOHM', 'IL');"
"insert into event_markets (event_code, market) values ('EVEXWBZYHUYSD', 'MN');"
"insert into event_markets (event_code, market) values ('EVEXXOAPAUMDF', 'MI');"
"insert into event_markets (event_code, market) values ('EVEXYZQLLRWYJ', 'MN');"
"insert into event_markets (event_code, market) values ('EVEYABHLKLFFQ', 'OH');"
"insert into event_markets (event_code, market) values ('EVEYCJOLQEJJV', 'IL');"
"insert into event_markets (event_code, market) values ('EVEYHLFSAXFRA', 'MN');"
"insert into event_markets (event_code, market) values ('EVEYJDIFVDEQX', 'IL');"
"insert into event_markets (event_code, market) values ('EVEYMCYRTBDHA', 'TX');"
"insert into event_markets (event_code, market) values ('EVEYOQYAHAWMF', 'MN');"
"insert into event_markets (event_code, market) values ('EVEYOYYKVENEV', 'TX');"
"insert into event_markets (event_code, market) values ('EVEYSTZIMTREU', 'TX');"
"insert into event_markets (event_code, market) values ('EVEYVEMPAUOUP', 'TX');"
"insert into event_markets (event_code, market) values ('EVEYVYSYBITVD', 'TX');"
"insert into event_markets (event_code, market) values ('EVEYWESUJZXYU', 'MN');"
"insert into event_markets (event_code, market) values ('EVEZCASOEGKMS', 'MI');"
"insert into event_markets (event_code, market) values ('EVEZDSERCJYET', 'MN');"
"insert into event_markets (event_code, market) values ('EVEZMRZHDDVJF', 'MN');"
"insert into event_markets (event_code, market) values ('EVEZSLFOLIGMT', 'MN');"
"insert into event_markets (event_code, market) values ('EVEZTGIASMDEB', 'MN');"
"insert into event_markets (event_code, market) values ('EVEZUAZLFAGKX', 'IL');"
"insert into event_markets (event_code, market) values ('EVEZUGKPEHLCR', 'MN');"
"insert into event_markets (event_code, market) values ('EVEZXXAKHEJNR', 'MN');"

?column?
"insert into company_aliases (from_key, to_key) values ('abel design group architects', 'abel design');"
"insert into company_aliases (from_key, to_key) values ('alamo title dfw', 'alamo title');"
"insert into company_aliases (from_key, to_key) values ('allied fire protection com', 'allied fire protection');"
"insert into company_aliases (from_key, to_key) values ('altus', 'altus group');"
"insert into company_aliases (from_key, to_key) values ('altus group limited', 'altus group');"
"insert into company_aliases (from_key, to_key) values ('anchor construction and management', 'anchor construction');"
"insert into company_aliases (from_key, to_key) values ('apartmentdata com from mri software', 'apartmentdata com');"
"insert into company_aliases (from_key, to_key) values ('arco murray design build', 'arco murray');"
"insert into company_aliases (from_key, to_key) values ('ascension', 'ascension commercial real estate');"
"insert into company_aliases (from_key, to_key) values ('ascension commercia real estate', 'ascension commercial real estate');"
"insert into company_aliases (from_key, to_key) values ('avison young commercial real estate', 'avison young');"
"insert into company_aliases (from_key, to_key) values ('berkshire hathaway texas realty', 'berkshire hathaway');"
"insert into company_aliases (from_key, to_key) values ('blusky restoration contractors', 'blusky restoration');"
"insert into company_aliases (from_key, to_key) values ('boka powell architects', 'boka powell');"
"insert into company_aliases (from_key, to_key) values ('boxer property management', 'boxer property');"
"insert into company_aliases (from_key, to_key) values ('boxer property managment', 'boxer property');"
"insert into company_aliases (from_key, to_key) values ('bradford', 'bradford commercial real estate');"
"insert into company_aliases (from_key, to_key) values ('bradford commercial', 'bradford commercial real estate');"
"insert into company_aliases (from_key, to_key) values ('bradford commercial real estate services', 'bradford commercial real estate');"
"insert into company_aliases (from_key, to_key) values ('bradford commercial realty', 'bradford commercial real estate');"
"insert into company_aliases (from_key, to_key) values ('bradford companies', 'bradford commercial real estate');"
"insert into company_aliases (from_key, to_key) values ('brookfield properties retail', 'brookfield properties');"
"insert into company_aliases (from_key, to_key) values ('cadence mcshane construction company', 'cadence mcshane construction');"
"insert into company_aliases (from_key, to_key) values ('capital title commercial', 'capital title');"
"insert into company_aliases (from_key, to_key) values ('capital title of texas', 'capital title');"
"insert into company_aliases (from_key, to_key) values ('cardinal capital partners', 'cardinal capital');"
"insert into company_aliases (from_key, to_key) values ('cbre dunn industrial', 'cbre');"
"insert into company_aliases (from_key, to_key) values ('central texas commercial association of realtors ctcar', 'central texas commercial association of realtors');"
"insert into company_aliases (from_key, to_key) values ('chicago title houston', 'chicago title');"
"insert into company_aliases (from_key, to_key) values ('city of anna edc', 'city of anna');"
"insert into company_aliases (from_key, to_key) values ('city of cedar park texas', 'city of cedar park');"
"insert into company_aliases (from_key, to_key) values ('city of sugar land economic development', 'city of sugar land');"
"insert into company_aliases (from_key, to_key) values ('civitas capital management', 'civitas capital');"
"insert into company_aliases (from_key, to_key) values ('colliers international', 'colliers');"
"insert into company_aliases (from_key, to_key) values ('colliers mortgage', 'colliers');"
"insert into company_aliases (from_key, to_key) values ('crew dallas sl taylor investments', 'crew dallas');"
"insert into company_aliases (from_key, to_key) values ('disrupt equity partners', 'disrupt equity');"
"insert into company_aliases (from_key, to_key) values ('dunaway associates', 'dunaway');"
"insert into company_aliases (from_key, to_key) values ('e e reed construction l p', 'e e reed construction');"
"insert into company_aliases (from_key, to_key) values ('ebby halliday realtors', 'ebby halliday');"
"insert into company_aliases (from_key, to_key) values ('ecr | equitable commercial realty', 'ecr');"
"insert into company_aliases (from_key, to_key) values ('enterprise bank trust', 'enterprise bank');"
"insert into company_aliases (from_key, to_key) values ('fidelis realty partners', 'fidelis');"
"insert into company_aliases (from_key, to_key) values ('fidelity national title dallas fort worth', 'fidelity national title');"
"insert into company_aliases (from_key, to_key) values ('fidelity national title ncs', 'fidelity national title');"
"insert into company_aliases (from_key, to_key) values ('foresite commercial real estate', 'foresite');"
"insert into company_aliases (from_key, to_key) values ('foresite cre', 'foresite');"
"insert into company_aliases (from_key, to_key) values ('fort worth chamber of commerce', 'fort worth chamber');"
"insert into company_aliases (from_key, to_key) values ('frisco economic development council', 'frisco economic development');"
"insert into company_aliases (from_key, to_key) values ('frontier title commercial', 'frontier title');"
"insert into company_aliases (from_key, to_key) values ('frost bank springwoods village', 'frost bank');"
"insert into company_aliases (from_key, to_key) values ('goosehead insurance the nolen agency', 'goosehead insurance');"
"insert into company_aliases (from_key, to_key) values ('goree architects', 'goree');"
"insert into company_aliases (from_key, to_key) values ('heights venture architecture + design', 'heights venture');"
"insert into company_aliases (from_key, to_key) values ('hudson peters commercial', 'hudson peters');"
"insert into company_aliases (from_key, to_key) values ('hunington properties', 'hunington');"
"insert into company_aliases (from_key, to_key) values ('infinity mep engineering', 'infinity mep');"
"insert into company_aliases (from_key, to_key) values ('institutional property advisors ipa', 'institutional property advisors');"
"insert into company_aliases (from_key, to_key) values ('interprise design', 'interprise');"
"insert into company_aliases (from_key, to_key) values ('interprise southwest interior space design', 'interprise');"
"insert into company_aliases (from_key, to_key) values ('jll capital markets', 'jll');"
"insert into company_aliases (from_key, to_key) values ('jll houston', 'jll');"
"insert into company_aliases (from_key, to_key) values ('kairoi residential', 'kairoi');"
"insert into company_aliases (from_key, to_key) values ('keen realty management', 'keen realty');"
"insert into company_aliases (from_key, to_key) values ('kfm engineering design', 'kfm');"
"insert into company_aliases (from_key, to_key) values ('kirksey architects', 'kirksey');"
"insert into company_aliases (from_key, to_key) values ('kirksey architecture', 'kirksey');"
"insert into company_aliases (from_key, to_key) values ('kt ventures tx', 'kt ventures');"
"insert into company_aliases (from_key, to_key) values ('landpark advisors', 'landpark');"
"insert into company_aliases (from_key, to_key) values ('lane property tax advisors', 'lane property tax');"
"insert into company_aliases (from_key, to_key) values ('lane property tax advocates', 'lane property tax');"
"insert into company_aliases (from_key, to_key) values ('langan engineering and environmental services', 'langan');"
"insert into company_aliases (from_key, to_key) values ('lee associates houston', 'lee associates');"
"insert into company_aliases (from_key, to_key) values ('legacy trust company n a', 'legacy trust');"
"insert into company_aliases (from_key, to_key) values ('lockt access controls', 'lockt');"
"insert into company_aliases (from_key, to_key) values ('marcus millichap capital', 'marcus millichap');"
"insert into company_aliases (from_key, to_key) values ('matthews', 'matthews real estate investment services');"
"insert into company_aliases (from_key, to_key) values ('matthews real estate', 'matthews real estate investment services');"
"insert into company_aliases (from_key, to_key) values ('matthews reis', 'matthews real estate investment services');"
"insert into company_aliases (from_key, to_key) values ('multivista documentation technologies', 'multivista');"
"insert into company_aliases (from_key, to_key) values ('nai robert lynn', 'nai robert');"
"insert into company_aliases (from_key, to_key) values ('net lease capital advisors', 'net lease capital');"
"insert into company_aliases (from_key, to_key) values ('newmark title', 'newmark');"
"insert into company_aliases (from_key, to_key) values ('newmark title services', 'newmark');"
"insert into company_aliases (from_key, to_key) values ('north texas ccim chapter', 'north texas ccim');"
"insert into company_aliases (from_key, to_key) values ('northmarq capital', 'northmarq');"
"insert into company_aliases (from_key, to_key) values ('ntcar the north texas commercial association of realtors', 'ntcar');"
"insert into company_aliases (from_key, to_key) values ('paladin partners commercial real estate services', 'paladin partners');"
"insert into company_aliases (from_key, to_key) values ('patel gaines attorneys at law', 'patel gaines');"
"insert into company_aliases (from_key, to_key) values ('patten title river oaks', 'patten title');"
"insert into company_aliases (from_key, to_key) values ('re journals', '__internal__');"
"insert into company_aliases (from_key, to_key) values ('read king commercial real estate', 'read king');"
"insert into company_aliases (from_key, to_key) values ('rednews', '__internal__');"
"insert into company_aliases (from_key, to_key) values ('rejournals', '__internal__');"
"insert into company_aliases (from_key, to_key) values ('revs refuel ev solutions', 'revs');"
"insert into company_aliases (from_key, to_key) values ('rutledge commercial real estate', 'rutledge commercial');"
"insert into company_aliases (from_key, to_key) values ('sands investment group sig', 'sands investment');"
"insert into company_aliases (from_key, to_key) values ('security service title compnay', 'security service title');"
"insert into company_aliases (from_key, to_key) values ('spirit realty capital', 'spirit realty');"
"insert into company_aliases (from_key, to_key) values ('srs real estate partners', 'srs real estate');"
"insert into company_aliases (from_key, to_key) values ('stewart title guaranty', 'stewart title');"
"insert into company_aliases (from_key, to_key) values ('stewart title national commercial services', 'stewart title');"
"insert into company_aliases (from_key, to_key) values ('stewart title ncs', 'stewart title');"
"insert into company_aliases (from_key, to_key) values ('stream realty', 'stream realty partners');"
"insert into company_aliases (from_key, to_key) values ('stream realty partners houston', 'stream realty partners');"
"insert into company_aliases (from_key, to_key) values ('strive real estate', 'strive');"
"insert into company_aliases (from_key, to_key) values ('suddath companies`', 'suddath');"
"insert into company_aliases (from_key, to_key) values ('suddath workplace solutions', 'suddath');"
"insert into company_aliases (from_key, to_key) values ('svn j beard real estate greater houston', 'svn j beard real estate');"
"insert into company_aliases (from_key, to_key) values ('tbd management wan bridge', 'tbd management');"
"insert into company_aliases (from_key, to_key) values ('terracon consultants', 'terracon');"
"insert into company_aliases (from_key, to_key) values ('texas built construction century 21 judge fite', 'texas built construction');"
"insert into company_aliases (from_key, to_key) values ('the development corporation of abilene dcoa', 'the development corporation of abilene');"
"insert into company_aliases (from_key, to_key) values ('the houston', 'the houston group');"
"insert into company_aliases (from_key, to_key) values ('the houston group realty advisors', 'the houston group');"
"insert into company_aliases (from_key, to_key) values ('the real estate council of greater fort worth rec of gfw', 'the real estate council of greater fort worth');"
"insert into company_aliases (from_key, to_key) values ('the wilkie team harvest', 'the wilkie team');"
"insert into company_aliases (from_key, to_key) values ('transwestern development', 'transwestern');"
"insert into company_aliases (from_key, to_key) values ('transwestern investment', 'transwestern');"
"insert into company_aliases (from_key, to_key) values ('trec real estate council', 'trec');"
"insert into company_aliases (from_key, to_key) values ('usi', 'usi insurance services');"
"insert into company_aliases (from_key, to_key) values ('usi insurance', 'usi insurance services');"
"insert into company_aliases (from_key, to_key) values ('vigavi realty', 'vigavi');"
"insert into company_aliases (from_key, to_key) values ('wells fargo bank', 'wells fargo');"
"insert into company_aliases (from_key, to_key) values ('wfg national title insurance', 'wfg national title');"
"insert into company_aliases (from_key, to_key) values ('xag', 'xag group');"
"insert into company_aliases (from_key, to_key) values ('xag properties', 'xag group');"